#!/bin/sh
#
# Copyright (C) 2017,2018 Ken'ichi Fukamachi
#   All rights reserved. This program is free software; you can
#   redistribute it and/or modify it under 2-Clause BSD License.
#   https://opensource.org/licenses/BSD-2-Clause
# 
# mailto: fukachan@fml.org
#    web: http://www.fml.org/
#
# $FML$
# $Revision$
#        NAME: git-cvsimport-log-parse.sh
# DESCRIPTION: parse the log file generated by "git cvsimport"
#              to only the most important messages only.
#

for f in $*
do
  egrep -v 'cvs rlog: |Logging |^Fetching |^New |^Update |^Parent ID |^Committed patch [0123456789]|^Commit ID |^Tree ID |^Parent ID |^Delete |^Created tag |^Merge parent branch:|^WARNING: revision .* on unnamed branch|^skip patchset [0123456789]|^Skipping #CVSPS_NO_BRANCH' $f
done

exit 0;
